export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCESS='USER_LOGIN_SUCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'
export const USER_LOGOUT='USER_LOGOUT'
export const USER_SIGNUP_REQUEST='USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS='USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL='USER_SIGNUP_FAIL'





